version: 2.1

jobs:
  validate-changes:
    docker:
      # pre-commit package is included since 20.10
      - image: ubuntu:20.10
    steps:
      - checkout
      - attach_platform:
          at: .
      - run:
          name: Run pre-commit checks
          command: |
            apt update && apt install -y shellcheck pre-commit git
            pre-commit run --all-files
  platform-base:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            ./.circleci/build_image.sh base/Dockerfile bhojpur/platform-base
            docker save bhojpur/platform-base -o platform-base.tar
          no_output_timeout: 20m
      - persist_to_platform:
          root: .
          paths:
            - platform-base.tar

  platform-full:
    docker:
      - image: bhojpur/ara:latest
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-base.tar
            ./.circleci/ara_build_image.sh full/Dockerfile bhojpur/platform-full platform-full.tar
          no_output_timeout: 30m
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/ara/
            cp full/*.xml ~/test-results/ara
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/ara
      - persist_to_platform:
          root: .
          paths:
            - platform-full.tar

  platform-full-vnc:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-full.tar
            ./.circleci/build_image.sh full-vnc/Dockerfile bhojpur/platform-full-vnc
            docker save bhojpur/platform-full-vnc -o platform-full-vnc.tar
      - persist_to_platform:
          root: .
          paths:
            - platform-full-vnc.tar

  mdbook:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-full.tar
            ./.circleci/build_image.sh mdbook/Dockerfile bhojpur/mdbook
          no_output_timeout: 30m

  platform-dotnet:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-full.tar
            ./.circleci/build_image.sh dotnet/Dockerfile bhojpur/platform-dotnet
          no_output_timeout: 60m

  platform-dotnet-vnc:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-full-vnc.tar
            ./.circleci/build_image.sh dotnet-vnc/Dockerfile bhojpur/platform-dotnet-vnc
          no_output_timeout: 30m

  platform-dotnet-lts:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-full.tar
            ./.circleci/build_image.sh dotnet-lts/Dockerfile bhojpur/platform-dotnet-lts
          no_output_timeout: 60m

  platform-dotnet-lts-vnc:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-full-vnc.tar
            ./.circleci/build_image.sh dotnet-lts-vnc/Dockerfile bhojpur/platform-dotnet-lts-vnc
          no_output_timeout: 30m

  platform-postgres:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-full.tar
            ./.circleci/build_image.sh postgres/Dockerfile bhojpur/platform-postgres
          no_output_timeout: 30m

  platform-mysql:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-full.tar
            ./.circleci/build_image.sh mysql/Dockerfile bhojpur/platform-mysql
          no_output_timeout: 30m

  platform-mongodb:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-full.tar
            ./.circleci/build_image.sh mongodb/Dockerfile bhojpur/platform-mongodb
  platform-flutter:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-full.tar
            ./.circleci/build_image.sh flutter/Dockerfile bhojpur/platform-flutter
  applicaiton-gecko:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-full-vnc.tar
            ./.circleci/build_image.sh gecko/Dockerfile bhojpur/platform-gecko
          no_output_timeout: 60m

  platform-wasm:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_platform:
          at: .
      - run:
          command: |
            docker load -i platform-full.tar
            ./.circleci/build_image.sh wasm/Dockerfile bhojpur/applicaiton-wasm
          no_output_timeout: 30m

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate-changes
      - platform-base:
          requires:
            - validate-changes
      - platform-full:
          requires:
            - platform-base
      - platform-full-vnc:
          requires:
            - platform-full
      - mdbook:
          requires:
            - platform-full
      - platform-dotnet:
          requires:
            - platform-full
      - platform-dotnet-vnc:
          requires:
            - platform-full-vnc
      - platform-dotnet-lts:
          requires:
            - platform-full
      - platform-dotnet-lts-vnc:
          requires:
            - platform-full-vnc
      - platform-postgres:
          requires:
            - platform-full
      - platform-mysql:
          requires:
            - platform-full
      - platform-mongodb:
          requires:
            - platform-full
      - platform-flutter:
          requires:
            - platform-full
      - platform-gecko:
          requires:
            - platform-full-vnc
      - platform-wasm:
          requires:
            - platform-full
