#!/bin/bash

set -o errexit

if [ $# = 0 ]; then
  echo >&2 "No packages specified"
  exit 1
fi

# Set a runlevel to avoid invoke-rc.d warnings
# http://manpages.ubuntu.com/manpages/focal/man8/runlevel.8.html#environment
# shellcheck disable=SC2034
RUNLEVEL=1

# shellcheck disable=SC2034
DEBIAN_FRONTEND=noninteractive

ARA_MARKS="/var/lib/apt/ara-marks/"
TIMESTAMP=$(date +%s)

if [ ! -d "${ARA_MARKS}" ]; then
  mkdir -p "${ARA_MARKS}"
fi

apt-get update
apt-get install -yq --no-install-recommends "$@"

cp /var/lib/dpkg/status "${ARA_MARKS}/${TIMESTAMP}.status"

apt-get clean -y

rm -rf \
   /var/cache/debconf/* \
   /var/lib/apt/lists/* \
   /tmp/* \
   /var/tmp/*
